### ISSUE TITLE
did you consider if system is mounted on multiple disk partions?

### ISSUE THREAD

**Issue by npumsy** [Jrebort/Linux-System-BackupScript#1]
My ubuntu system has 4 mount point: / , /boot, /home, and /boot/efi, each from disk partition /dev/sda3, /dev/sda2, /dev/sdc4, /dev/sda1. I read your file bksys.shell，and not sure whether it will pack all the file from these partions into one compressed file. If its recovered from the file, whether it would unpack the one file into former multiple partions.

**Comment by Jrebort** [comment]
Yes, all that mount point can be backup by this shell script, it only cares directory structure.

**Comment by Jrebort** [comment]
the issue is solved.
